spring:
  application:
    name: hrm-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/drishti
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true